// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6YI4y1N6gH0Byjl58ZrIuqkylaC9w9M',
    appId: '1:236885951067:web:bf63e7cdae3eca2f35357e',
    messagingSenderId: '236885951067',
    projectId: 'switch-on-coffee-and-keto',
    authDomain: 'switch-on-coffee-and-keto.firebaseapp.com',
    databaseURL: 'https://switch-on-coffee-and-keto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'switch-on-coffee-and-keto.appspot.com',
    measurementId: 'G-LJJPQNM67F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPQY_r_mv5H7-xo-mBomv8wLXtYjtvvk',
    appId: '1:236885951067:android:51e937edf0b365cd35357e',
    messagingSenderId: '236885951067',
    projectId: 'switch-on-coffee-and-keto',
    databaseURL: 'https://switch-on-coffee-and-keto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'switch-on-coffee-and-keto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf7ITmm2Cnru6mnYs-NmJjrw4-KwaQlqQ',
    appId: '1:236885951067:ios:03a1820b375c4ebd35357e',
    messagingSenderId: '236885951067',
    projectId: 'switch-on-coffee-and-keto',
    databaseURL: 'https://switch-on-coffee-and-keto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'switch-on-coffee-and-keto.appspot.com',
    iosClientId: '236885951067-8j2jtd5lfqkard4qbm31l9gj9ns507up.apps.googleusercontent.com',
    iosBundleId: 'com.happysoft.switchonkitchenscreen',
  );
}
